### ISSUE TITLE
Countdown mode

### ISSUE THREAD

**Issue by ocarreterom** [stimulus-components/stimulus-character-counter#2]
It's common to view the reverse behavior: a countdown from `maxlength` to 0.

Could it be added to this component as an option like `character-counter-countdown` or `character-counter-inverse`, or should it be a new component like `character-countdown`?

**Comment by guillaumebriday** [comment]
@ocarreterom Did you think of something like that: https://github.com/stimulus-components/stimulus-character-counter/pull/4?

**Comment by guillaumebriday** [comment]
Done here https://github.com/stimulus-components/stimulus-character-counter/commit/18f054f5298ded439cc4ea28321b47ad7725a936

Thanks for the suggestion
